### ISSUE TITLE
API Login - Server error, status code: 404, error code

### ISSUE THREAD

**Issue by abhaychaware** [aws-quickstart/quickstart-pivotal-cloudfoundry#12]
I have the PCF QuickStart environment setup correctly on AWS cloud, i am able to access opsman on web, but when i try login using the CF CLI API, 

cf login -a https://api.pcf.xxxxxxxxxx.com -u admin --skip-ssl-validation

i am getting this error message

> cf login -a https://api.pcf.xxxxxxxxxx.com -u admin --skip-ssl-validation
> API endpoint: https://api.pcf.xxxxxxxxxx.com
> FAILED
> Server error, status code: 404, error code: 0, message:

Am I missing anything ?

-abhay

**Comment by platinumnj** [comment]
Have you made sure that your using a wild card SSL certificate?

**Comment by abhaychaware** [comment]
This is what I have in the AWS Certificate manager that is used in this deployment - 

Type	Imported
In use?	Yes
Domain name	*.pcf.xxxxxxxxx.com
Number of additional names	4
Additional names	*.sys.pcf.xxxxxxxxx.com, *.apps.pcf.xxxxxxxxx.com, *.login.sys.pcf.xxxxxxxxx.com, *.uaa.sys.pcf.xxxxxxxxx.com

Is that enough?

-abhay

**Comment by platinumnj** [comment]
That looks pretty accurate.

**Comment by boparp-pivotal** [comment]
The API endpoint is always api.[YOUR SYS DOMAIN], so in your case it should be: 
cf login -a https://api.sys.pcf.xxxxxxxxxx.com -u admin --skip-ssl-validation

**Comment by abhaychaware** [comment]
This worked !  Thanks. 

Looks like the Quick Start for AWS PDF document needs an update ?  See attached.

![cli login](https://user-images.githubusercontent.com/4303899/33866776-9f7e9916-df1e-11e7-828b-be1d4cbd7348.JPG)


Thanks
Abhay

**Comment by boparp-pivotal** [comment]
Thanks for the feedback. We'll fix the doc.

**Comment by boparp-pivotal** [comment]
The document is updated.

**Comment by abhaychaware** [comment]
Thanks !!
