### ISSUE TITLE
ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack

### ISSUE THREAD

**Issue by hexaforce** [aws-quickstart/quickstart-pivotal-cloudfoundry#16]
I tried it with ap-northeast-1 but it fails.

10:36:17 UTC+0900	ROLLBACK_FAILED	AWS::CloudFormation::Stack	HexaForceCloud	The following resource(s) failed to delete: [SSMParameterJSON].
10:36:16 UTC+0900	DELETE_COMPLETE	AWS::CloudFormation::Stack	PCFBase	
10:21:29 UTC+0900	DELETE_IN_PROGRESS	AWS::CloudFormation::Stack	PCFBase	
10:21:25 UTC+0900	DELETE_COMPLETE	AWS::EC2::Instance	OpsManagerInstance	
10:20:39 UTC+0900	DELETE_COMPLETE	AWS::IAM::Policy	PCFDescribeStackPolicy	
10:20:39 UTC+0900	DELETE_COMPLETE	AWS::IAM::Policy	PCFParameterStorePolicy	
10:20:39 UTC+0900	DELETE_COMPLETE	AWS::IAM::Policy	PCFEmitLogsPolicy	
10:20:37 UTC+0900	DELETE_IN_PROGRESS	AWS::IAM::Policy	PCFEmitLogsPolicy	
10:20:37 UTC+0900	DELETE_IN_PROGRESS	AWS::IAM::Policy	PCFDescribeStackPolicy	
10:20:37 UTC+0900	DELETE_IN_PROGRESS	AWS::EC2::Instance	OpsManagerInstance	
10:20:37 UTC+0900	DELETE_IN_PROGRESS	AWS::IAM::Policy	PCFParameterStorePolicy	
10:20:36 UTC+0900	DELETE_COMPLETE	AWS::EC2::Instance	BootstrapInstance	
10:19:07 UTC+0900	DELETE_IN_PROGRESS	AWS::EC2::Instance	BootstrapInstance	
10:19:05 UTC+0900	DELETE_COMPLETE	AWS::EC2::EIP	OpsManagerEIP	
10:19:05 UTC+0900	DELETE_COMPLETE	AWS::EC2::EIP	BootstrapEIP	
10:18:47 UTC+0900	DELETE_IN_PROGRESS	AWS::EC2::EIP	OpsManagerEIP	
10:18:47 UTC+0900	DELETE_IN_PROGRESS	AWS::EC2::EIP	BootstrapEIP	
10:18:45 UTC+0900	DELETE_COMPLETE	AWS::Route53::RecordSet	DNS	
10:18:45 UTC+0900	DELETE_COMPLETE	AWS::Route53::RecordSet	DNSOpsMan	
10:18:45 UTC+0900	DELETE_COMPLETE	AWS::SQS::Queue	CustomResourceSQSQueue	
10:18:45 UTC+0900	DELETE_COMPLETE	AWS::Route53::RecordSet	DNSSys	
10:18:45 UTC+0900	DELETE_COMPLETE	AWS::Route53::RecordSet	DNSApps	
10:18:45 UTC+0900	DELETE_COMPLETE	AWS::Route53::RecordSet	DNSStar	
10:17:45 UTC+0900	DELETE_IN_PROGRESS	AWS::SQS::Queue	CustomResourceSQSQueue	
10:17:44 UTC+0900	DELETE_COMPLETE	AWS::CloudFormation::WaitConditionHandle	WaitHandle	
10:17:44 UTC+0900	DELETE_COMPLETE	AWS::IAM::AccessKey	PcfIamUserAccessKey	
10:17:43 UTC+0900	DELETE_IN_PROGRESS	AWS::IAM::AccessKey	PcfIamUserAccessKey	
10:17:43 UTC+0900	DELETE_IN_PROGRESS	AWS::CloudFormation::WaitConditionHandle	WaitHandle	
10:17:43 UTC+0900	DELETE_COMPLETE	AWS::SNS::Topic	CustomResourceSNSTopic	
10:17:42 UTC+0900	DELETE_IN_PROGRESS	AWS::SNS::Topic	CustomResourceSNSTopic	
10:17:41 UTC+0900	DELETE_FAILED	AWS::SSM::Parameter	SSMParameterJSON	The security token included in the request is invalid (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 644d5ef1-f27f-11e7-83c1-770df3e39d44)
10:17:41 UTC+0900	DELETE_COMPLETE	AWS::IAM::Policy	PCFCustomResourcePolicy	
10:17:40 UTC+0900	DELETE_COMPLETE	AWS::SQS::QueuePolicy	CustomResourceSQSQueuePolicy	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::Route53::RecordSet	DNSOpsMan	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::IAM::Policy	PCFCustomResourcePolicy	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::Route53::RecordSet	DNS	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::Route53::RecordSet	DNSApps	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::SSM::Parameter	SSMParameterJSON	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::Route53::RecordSet	DNSSys	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::Route53::RecordSet	DNSStar	
10:17:39 UTC+0900	DELETE_IN_PROGRESS	AWS::SQS::QueuePolicy	CustomResourceSQSQueuePolicy	
10:17:36 UTC+0900	DELETE_COMPLETE	Custom::BOSH	MyCustomBOSH	
10:11:58 UTC+0900	DELETE_COMPLETE	AWS::Route53::RecordSet	DNSSsh	
10:10:52 UTC+0900	DELETE_COMPLETE	AWS::CloudFormation::WaitCondition	WaitCondition	
10:10:52 UTC+0900	DELETE_IN_PROGRESS	Custom::BOSH	MyCustomBOSH	
10:10:52 UTC+0900	DELETE_IN_PROGRESS	AWS::Route53::RecordSet	DNSSsh	
10:10:52 UTC+0900	DELETE_IN_PROGRESS	AWS::CloudFormation::WaitCondition	WaitCondition	
10:10:46 UTC+0900	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	HexaForceCloud	The following resource(s) failed to create: [WaitCondition]. . Rollback requested by user.
10:10:43 UTC+0900	CREATE_FAILED	AWS::CloudFormation::WaitCondition	WaitCondition	Unparsable WaitCondition data

**Comment by boparp-pivotal** [comment]
Did you turn on the CloudWatch logs? If not, can you try a fresh deploy and capture the logs in CloudWatch and share? 
Did you increase your AWS quota limits to meet the requirements?

**Comment by hexaforce** [comment]
CloudWatch has been disabled.
Ok. I will try again.

**Comment by hexaforce** [comment]
It will roll back after this

-----------------------------------------------------------------------------
09:04:18	Director task 82 Started preparing deployment > Preparing deployment. Done (00:00:02) Started preparing package compilation > Finding packages to compile. Done (00:00:00) Started creating missing vms Started creating missing vms > doppler/08827361-5be8-455a-b4c7-d54b4ce4b27d (0) Started creating missing vms > tcp_router/ac96fd74-1dc9-48e0-aac4-3f8efe7aa5da (0). Failed: Unknown CPI erro
09:04:18	Error 100: Unknown CPI error 'Unknown' with message 'Your quota allows for 0 more running instance(s). You requested at least 1' in 'create_vm' CPI method
09:04:18	Task 82 error
09:04:18	For a more detailed error report, run: bosh task 82 --debug
09:04:18	===== 2018-01-06 09:04:11 UTC Finished "bundle exec bosh -n deploy"; Duration: 72s; Exit Status: 1
09:04:18	{"type": "step_finished", "id": "bosh.deploying.cf-5fd688dca30c1b7c5877"}
09:04:18	Exited with 1.
09:04:18	error: could not execute "apply-changes": installation was unsuccessful
09:04:18	Sleeping 1
09:04:18	Running: om -k --target https://opsman.pcf.hexaforce.io --username 'admin' --password '*****************' apply-changes
-----------------------------------------------------------------------------

No matter how many times I try, I have failed here
[Installing Pivotal Elastic Runtime]

-----------------------------------------------------------------------------
  Started creating missing vms > doppler/08827361-5be8-455a-b4c7-d54b4ce4b27d (0)
     Done creating missing vms > diego_cell/528cf4c8-b0b4-4643-8a29-df91a2414ad1 (2) (00:01:25)
  Started creating missing vms > tcp_router/ac96fd74-1dc9-48e0-aac4-3f8efe7aa5da (0)
   Failed creating missing vms > doppler/08827361-5be8-455a-b4c7-d54b4ce4b27d (0): Unknown CPI error 'Unknown' with message 'Your quota allows for 0 more running instance(s). You requested at least 1' in 'create_vm' CPI method (00:00:09)
   Failed creating missing vms > tcp_router/ac96fd74-1dc9-48e0-aac4-3f8efe7aa5da (0): Unknown CPI error 'Unknown' with message 'Your quota allows for 0 more running instance(s). You requested at least 1' in 'create_vm' CPI method (00:00:08)
     Done creating missing vms > diego_cell/bcf7afcc-675f-40ea-a0a1-302039a156d2 (1) (00:01:12)
     Done creating missing vms > loggregator_trafficcontroller/74ee4f07-36c9-4963-a05b-4e4cee957dcf (0) (00:01:22)
     Done creating missing vms > syslog_adapter/a8edfa9f-a503-481c-bbf2-1776cfa7152d (0) (00:01:16)
     Done creating missing vms > syslog_scheduler/dbd86366-35b0-4913-a4de-0b05253c4b02 (0) (00:01:22)
   Failed creating missing vms (00:04:40)

Error 100: Unknown CPI error 'Unknown' with message 'Your quota allows for 0 more running instance(s). You requested at least 1' in 'create_vm' CPI method

Task 44 error

For a more detailed error report, run: bosh task 44 --debug
===== 2018-01-06 09:00:07 UTC Finished "bundle exec bosh -n deploy"; Duration: 324s; Exit Status: 1
Exited with 1.
-----------------------------------------------------------------------------

**Comment by hexaforce** [comment]
By default ap-northeast-1 the EC 2 limit was 20.
I issued a request to change the limit now.
I will be able to move it this time.

Thank you.
