### ISSUE TITLE
Receiving Error - Parameter 'OpsManagerAdminPassword' must match pattern [\w-_]*

### ISSUE THREAD

**Issue by platinumnj** [aws-quickstart/quickstart-pivotal-cloudfoundry#9]
I am getting the following error when trying to deploy using cloud formation - 

Error

Template validation error: Parameter 'OpsManagerAdminPassword' must match pattern [\w-_]*

**Comment by jshah-pivotal** [comment]
passwords must be  at least 14 characters from the set of
alphanumeric, dashes, and underscores.

**Comment by platinumnj** [comment]
Thank you.... Issue resolved.
